version: '3.8'

services:
  auth-server:
    build:
      context: ./authserver
    ports:
      - "8080:8080"
    restart: always
    container_name: auth-server

  app1:
    build:
      context: ./app1
    ports:
      - "8081:8081"
    depends_on:
      - auth-server
    restart: always
    container_name: app1

  app2:
    build:
      context: ./app2
    ports:
      - "8082:8082"
    depends_on:
      - auth-server
    restart: always
    container_name: app2
